### ISSUE TITLE
change tab name 

### ISSUE THREAD

**Issue by VishRaj-MJ** [VishRaj-MJ/todotest#1]
when opened the upper tab shows localhost , change it to To-Do List

**Comment by Nienormalny** [comment]
Let me fix it

**Comment by Nienormalny** [comment]
![Screenshot_1](https://github.com/VishRaj-MJ/todotest/assets/22656923/ffd4cbb4-e9bf-4b80-a806-7a4dfa53a73f)
Can you add this?
